### ISSUE TITLE
service crashing during startup

### ISSUE THREAD

**Issue by BadWolf42** [nopap/nab2mqttd#1]
Hello,

Thank you for your work on this App !
I'm experiencing issues launching it.

_[DIAG]_
cloned in pynab -> OK
switched to venv -> OK
install paho-mqtt in venv -> OK
makemigrations -> OK
migrate -> OK
service & enable & start -> (warning regarding PID folder, but) OK
config in WebUI -> OK
service seems to be stuck in a crash-loop -> collected [LOG VAR]
doesn't even quite connect to MQTT
reboot (just in case)
service seems to be stuck in a crash-loop
service stop
switch to venv
lauched by hand (sudo /home/pi/pynab/venv/bin/python -m nab2mqttd.nab2mqttd)
 -> collected [LOG TERMINAL]

**Any idea ?**

_[LOG VAR]_
```
INFO 2020-11-25 19:00:05,150 nab2mqttd started
DEBUG 2020-11-25 19:00:07,755 Using selector: EpollSelector
DEBUG 2020-11-25 19:00:07,847 Config.server: 192.168.11.4
DEBUG 2020-11-25 19:00:07,850 Config.topic: nabaztag/coucou
INFO 2020-11-25 19:01:22,614 nab2mqttd started
DEBUG 2020-11-25 19:01:24,895 Using selector: EpollSelector
DEBUG 2020-11-25 19:01:24,985 Config.server: 192.168.11.4
DEBUG 2020-11-25 19:01:24,989 Config.topic: nabaztag/coucou
DEBUG 2020-11-25 19:01:25,045 Connected to MQTT with result code 0
DEBUG 2020-11-25 19:01:25,057 process nabd packet: {'type': 'state', 'state': 'idle'}
```

_[LOG TERMINAL]_
```
INFO 2020-11-25 19:01:22,614 nab2mqttd started
DEBUG 2020-11-25 19:01:24,895 Using selector: EpollSelector
DEBUG 2020-11-25 19:01:24,985 Config.server: 192.168.11.4
DEBUG 2020-11-25 19:01:24,989 Config.topic: nabaztag/coucou
DEBUG 2020-11-25 19:01:25,045 Connected to MQTT with result code 0
DEBUG 2020-11-25 19:01:25,057 process nabd packet: {'type': 'state', 'state': 'idle'}
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/pynab/nab2mqttd/nab2mqttd.py", line 139, in <module>
    Nab2MQTTd.main(sys.argv[1:])
  File "/home/pi/pynab/nabcommon/nabservice.py", line 186, in main
    service.run()
  File "/home/pi/pynab/nabcommon/nabservice.py", line 119, in run
    raise ex
  File "/home/pi/pynab/nabcommon/nabservice.py", line 300, in service_loop
    next_date, next_args, config = await self._load_config()
  File "/home/pi/pynab/nabcommon/nabservice.py", line 346, in _load_config
    saved_date, saved_args, config = await self.get_config()
  File "/home/pi/pynab/nab2mqttd/nab2mqttd.py", line 87, in get_config
    config = models.Config.load()
  File "/home/pi/pynab/nabcommon/singleton_model.py", line 39, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1150, in execute_sql
    cursor = self.connection.cursor()
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.

```

Thanks,
Bad Wolf

**Comment by nopap** [comment]
i'd say it's linled to the django update that was done a while back. Did you update all your pynab code ?
i'll try to retest locally and let you know

**Comment by BadWolf42** [comment]
Hello, thanks for your quick answer ! Yes last pynab version, I had issues with the previous one.

I actually made it work (see my repo), I intend to push a PR, with limited changes, to fix this issue first (as I went off road into non essential changes, doc, design...)
Then I'll send other PR to suggest the other changes "avec parcimonie" ;)

I'll keep you posted

**Comment by BadWolf42** [comment]
No longer relevant
