### ISSUE TITLE
Error: relation "nab2mqttd_config" does not exist

### ISSUE THREAD

**Issue by liouma** [nopap/nab2mqttd#3]
Hello,
Here is what I did as user 'pi', not 'root':

```
source /opt/pynab/venv/bin/activate
pip install paho-mqtt
cd /opt/pynab/
git clone https://github.com/nopap/nab2mqttd.git
```

note: In the new versions of pynab, it is installed in /opt/pynab/ and not /home/pi/pynab. 
-> I changed the path in nab2mqttd.service

```
sudo nano /home/pi/pynab/nabweb/settings.py		# Add nab2mqttd in INSTALLED_APPS and remove nabmastodond
tail /var/log/nab* -f &										# In another terminal
sudo cp nab2mqttd.service /lib/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable nab2mqttd.service
sudo systemctl stop nabmastodond.service
sudo systemctl disable nabmastodond.service
sudo systemctl restart nabweb.service
sudo systemctl status nab2mqttd.service
sudo systemctl start nab2mqttd.service
sudo reboot
```
The web UI is loading without the nab2mqttd section.
I get the following error in the log:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pynab/nabcommon/nabservice.py", line 201, in main
    service = cls()
  File "/opt/pynab/nab2mqttd/nab2mqttd.py", line 64, in __init__
    config = models.Config.load()
  File "/opt/pynab/nabcommon/singleton_model.py", line 39, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "nab2mqttd_config" does not exist
LINE 1: ..., "nab2mqttd_config"."next_performance_type" FROM "nab2mqttd...`
```

How is nab2mqttd_config supposed to be created?

Also 'status' gives me that:
```
(venv) pi@Nabaztag:/opt/pynab/nab2mqttd $ sudo systemctl status nab2mqttd.service
● nab2mqttd.service - Nabaztag 2 MQTT daemon
   Loaded: loaded (/lib/systemd/system/nab2mqttd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-11-29 09:08:19 +04; 1s ago
 Main PID: 7027 (python)
    Tasks: 1 (limit: 985)
   CGroup: /system.slice/nab2mqttd.service
           └─7027 /opt/pynab/venv/bin/python -m nab2mqttd.nab2mqttd

Nov 29 09:08:20 Nabaztag python[7027]:     return executor(sql, params, many, context)
Nov 29 09:08:20 Nabaztag python[7027]:   File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/backends/utils.py",
Nov 29 09:08:20 Nabaztag python[7027]:     return self.cursor.execute(sql, params)
Nov 29 09:08:20 Nabaztag python[7027]:   File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/utils.py", line 90,
Nov 29 09:08:20 Nabaztag python[7027]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Nov 29 09:08:20 Nabaztag python[7027]:   File "/opt/pynab/venv/lib/python3.7/site-packages/django/db/backends/utils.py",
Nov 29 09:08:20 Nabaztag python[7027]:     return self.cursor.execute(sql, params)
Nov 29 09:08:20 Nabaztag python[7027]: django.db.utils.ProgrammingError: relation "nab2mqttd_config" does not exist
Nov 29 09:08:20 Nabaztag python[7027]: LINE 1: ..., "nab2mqttd_config"."next_performance_type" FROM "nab2mqttd...
Nov 29 09:08:20 Nabaztag python[7027]:    
```

**Comment by lotooo** [comment]
I installed the plugin yesterday and added more info in https://www.tagtagtag.fr/forum/showthread.php?tid=69&pid=2692#pid2692

I think what is missing in your case : 

- `cd /opt/pynab`
- `source venv/bin/activate`
- `python manage.py makemigrations`
- `python manage.py migrate`

This should create the needed tables in the DB.

**Comment by liouma** [comment]
Thank you so much !!!
It works, now the web interface shows up :)
